### PR TITLE
SWARM-394: Enhancements to StartMojo

### PR DESCRIPTION
**Pull request by gastaldi**
Needed when executed from an embedded Maven (Forge addon)

### CODE REVIEW

**Comment by gastaldi** [comment]
@bobmcwhirter @kenfinnigan can you review this PR? I need it for the Forge addon.

Thanks!

**Comment by bobmcwhirter** [comment]
Shouldn't destroy be a part of :stop and not :start. Can't really tell on my phone.

**Comment by gastaldi** [comment]
Destroy should also be done when interrupted. That is never happening.

**Comment by gastaldi** [comment]
destroy is only called if waitForProcess= true and leaves the waitFor loop (when destroyed or interrupted)

**Comment by bobmcwhirter** [comment]
Ah. Sounds good then.

--
Sent from my iPhone


On Mar 30, 2016, at 5:35 PM, George Gastaldi <notifications@github.com>
wrote:

destroy is only called if waitForProcess= true and leaves the waitFor loop
(when destroyed or interrupted)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/pull/6#issuecomment-203644662>

**Comment by gastaldi** [comment]
Thank you!

**Pull request merged**
