### PR TITLE
[SWARM-315] Expose container & container-runtime through BOM

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Can you elaborate on why these need to be in the BOM?

From a users perspective, they won't ever need to refer to it directly

**Comment by tdiesler** [comment]
We have references to these here ...

https://github.com/wildfly-extras/wildfly-camel/blob/master/pom.xml#L364
https://github.com/wildfly-extras/wildfly-camel/blob/master/swarm/core/api/pom.xml#L47

Ideally, I'd just like to reference the BOM

**Comment by bobmcwhirter** [comment]
We tend to use org.wildfly.swarm:core as a parent Pom to get that.

**Comment by tdiesler** [comment]
ok, I'll try that

**Pull request closed without merging**
